<a href="https://colab.research.google.com/github/Adityabhor123/Data_Science_Lab/blob/main/DS_Practical3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
# PROGRAM 1
# Aim: To find determinant of a 3x3 matrix using NumPy (User Input)

import numpy as np

print("Enter elements of 3x3 matrix:")

matrix = []
for i in range(3):
    row = list(map(float, input(f"Enter row {i+1} elements separated by space: ").split()))
    matrix.append(row)

A = np.array(matrix)

print("\nMatrix A:")
print(A)

det = np.linalg.det(A)

print("\nDeterminant of matrix:", det)



Enter elements of 3x3 matrix:
Enter row 1 elements separated by space: 1 0 0
Enter row 2 elements separated by space: 0 1 0
Enter row 3 elements separated by space: 0 0 1

Matrix A:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Determinant of matrix: 1.0


In [14]:
# PROGRAM 1
# Aim: To find determinant of a 3x3 matrix without using NumPy (User Input)

print("Enter elements of 3x3 matrix:")

A = []
for i in range(3):
    row = list(map(float, input(f"Enter row {i+1} elements separated by space: ").split()))
    A.append(row)

det = (A[0][0]*(A[1][1]*A[2][2] - A[1][2]*A[2][1])
       - A[0][1]*(A[1][0]*A[2][2] - A[1][2]*A[2][0])
       + A[0][2]*(A[1][0]*A[2][1] - A[1][1]*A[2][0]))

print("\nDeterminant:", det)


Enter elements of 3x3 matrix:
Enter row 1 elements separated by space: 1 0 4
Enter row 2 elements separated by space: 5 0 9 
Enter row 3 elements separated by space: 1 2 6

Determinant: 22.0


In [24]:
# PROGRAM 2
# Aim: To find inverse of a 3x3 matrix without using NumPy (User Input)

# PROGRAM 2
# Aim: To find inverse of a 3x3 matrix without using NumPy (User Input)

print("Enter elements of 3x3 matrix:")

A = []
for i in range(3):
    while True:
        row = list(map(float, input(f"Enter 3 values for row {i+1}: ").split()))
        if len(row) == 3:
            A.append(row)
            break
        else:
            print("Please enter exactly 3 numbers.")

a, b, c = A[0]
d, e, f = A[1]
g, h, i = A[2]

# Determinant
det = a*(e*i - f*h) - b*(d*i - f*g) + c*(d*h - e*g)

if det == 0:
    print("\nMatrix is not invertible")
else:
    inv = [
        [(e*i - f*h)/det,  (c*h - b*i)/det,  (b*f - c*e)/det],
        [(f*g - d*i)/det,  (a*i - c*g)/det,  (c*d - a*f)/det],
        [(d*h - e*g)/det,  (b*g - a*h)/det,  (a*e - b*d)/det]
    ]

    print("\nInverse of the matrix:")
    for row in inv:
        print(row)


Enter elements of 3x3 matrix:
Enter 3 values for row 1: 2 3 6
Enter 3 values for row 2: 2 3 2
Enter 3 values for row 3: 2 4 8

Inverse of the matrix:
[2.0, 0.0, -1.5]
[-1.5, 0.5, 1.0]
[0.25, -0.25, 0.0]


In [19]:
# PROGRAM 2
# using numpy
import numpy as np

print("Enter elements of 3x3 matrix:")
A = np.array([[float(input(f"a[{i+1}][{j+1}]: ")) for j in range(3)] for i in range(3)])

print("\nInverse of the matrix:")
print(np.linalg.inv(A))







Enter elements of 3x3 matrix:
a[1][1]: 2
a[1][2]: 3
a[1][3]: 6
a[2][1]: 2
a[2][2]: 3
a[2][3]: 2
a[3][1]: 2
a[3][2]: 4
a[3][3]: 8

Inverse of the matrix:
[[ 2.    0.   -1.5 ]
 [-1.5   0.5   1.  ]
 [ 0.25 -0.25 -0.  ]]


In [10]:
# PROGRAM 3
# Aim: To solve the system of linear equations using NumPy
# Equations:
# 2x + 3y = 10
# 4x + 5y = 20

import numpy as np

# Coefficient matrix
A = np.array([[2, 3],
              [4, 5]])

# Constant matrix
B = np.array([10, 20])

# Solving equations
solution = np.linalg.solve(A, B)

print("x =", solution[0])
print("y =", solution[1])


x = 5.0
y = 0.0


In [11]:
# PROGRAM 3
# Aim: To solve the system of linear equations without using NumPy
# Using Cramer's Rule

a1, b1, c1 = 2, 3, 10
a2, b2, c2 = 4, 5, 20

# Determinant
D = a1*b2 - a2*b1

if D == 0:
    print("No unique solution")
else:
    Dx = c1*b2 - c2*b1
    Dy = a1*c2 - a2*c1

    x = Dx / D
    y = Dy / D

    print("x =", x)
    print("y =", y)


x = 5.0
y = -0.0
